#!/bin/sh
### BEGIN INIT INFO
# Provides:         kiwiirc
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:
# Required-Stop:
# Short-Description: KiwiIRC server
# Description:       Init script for KiwiIRC server
### END INIT INFO

dir="/var/lib/kiwiirc"
cmd="/usr/bin/kiwiirc"
args="--config=/etc/kiwiirc/config.conf"
user="kiwiirc"
group="kiwiirc"

name=kiwiirc #`basename $0`
pid_file="/var/run/$name.pid"
std_log="/var/log/$name.log"


calling_process=`ps -o comm= $PPID`
if [ "$calling_process" != "systemd" ]; then
    if command -v systemctl > /dev/null 2>&1 ; then
        systemctl $1 kiwiirc.service
        exit $?
    fi
fi


get_pid() {
    cat "$pid_file"
}

is_running() {
    [ -f "$pid_file" ] && ps `get_pid` > /dev/null 2>&1
}

case "$1" in
    start)
    if is_running; then
        echo "Already started"
    else
        echo "Starting $name"
        cd "$dir"
        touch $std_log
        chown $user:$group $std_log
        start-stop-daemon --start --quiet --chuid $user:$group --pidfile $pid_file --make-pidfile --exec $cmd -- $args 1>> "$std_log" 2>&1 &
        sleep 1;
        if ! is_running; then
            echo "Unable to start, see $std_log"
            exit 1
        fi
    fi
    ;;
    stop)
    if is_running; then
        echo -n "Stopping $name.."
        kill `get_pid`
        for i in {1..10}
        do
            if ! is_running; then
                break
            fi

            echo -n "."
            sleep 1
        done
        echo

        if is_running; then
            echo "Not stopped; may still be shutting down or shutdown may have failed"
            exit 1
        else
            echo "Stopped"
            if [ -f "$pid_file" ]; then
                rm "$pid_file"
            fi
        fi
    else
        echo "Not running"
    fi
    ;;
    restart)
    $0 stop
    if is_running; then
        echo "Unable to stop, will not attempt to start"
        exit 1
    fi
    $0 start
    ;;
    status)
    if is_running; then
        echo "Running"
    else
        echo "Stopped"
        exit 1
    fi
    ;;
    *)
    echo "Usage: $0 {start|stop|restart|status}"
    exit 1
    ;;
esac

exit 0
